import "server-only";

export {
  ROULETTE_BASE_WEIGHTS,
  ROULETTE_BOOSTED_WEIGHTS,
  ROULETTE_BOOST_BALANCE_CAP,
  ROULETTE_BOOST_COST,
  ROULETTE_COOLDOWN_MULTIPLIER,
  ROULETTE_COOLDOWN_ROUNDS,
  ROULETTE_ELIGIBLE_STATUSES,
  ROULETTE_MINIMUM_ELIGIBLE_GAMES,
  ROULETTE_PITY_THRESHOLD,
  ROULETTE_REEL_SLOT_COUNT,
  ROULETTE_RARITIES,
  ROULETTE_WEEKEND_BOOST_EARN_MULTIPLIER,
  applyBoostCostPolicy,
  applyCooldownWeights,
  applyPityTransition,
  buildVisualReel,
  calculateBoostEarnAmount,
  getEligiblePoolPolicy,
  getRoundResumePolicy,
  selectRouletteResult,
  type RouletteCooldown,
  type RouletteCooldownWeight,
  type RouletteEligiblePoolResult,
  type RouletteEligibleStatus,
  type RouletteGame,
  type RouletteLibraryStatus,
  type RouletteRarity,
  type RouletteRarityWeights,
  type RouletteRoundStatus,
  type RouletteSelectionResult,
  type RouletteVisualReelSlot
} from "./domain/roulette-policy";
