#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const workspaceRoot = resolve(scriptDir, "..");
const phaseDir = resolve(workspaceRoot, ".planning/phases/07-paridade-visual-e-ux-com-prototipo");
const evidencePath = resolve(phaseDir, "07-VISUAL-EVIDENCE.md");
const screenshotDir = resolve(phaseDir, "evidence/screenshots");
const pnpmBin = "pnpm";

loadEnvLocal();

const e2eFixtureVars = [
  "E2E_BASE_URL",
  "E2E_READY_USER_EMAIL",
  "E2E_READY_USER_PASSWORD"
];
const missingExternalEvidence = missingVars(e2eFixtureVars);

if (missingExternalEvidence.length > 0) {
  console.warn(
    `[phase:7:gate] BLOCKED - missing external evidence: ${missingExternalEvidence.join(", ")}.`
  );
}

const commands = [
  {
    args: ["check:secrets"],
    command: pnpmBin,
    name: "Secret scan"
  },
  {
    args: ["check:architecture"],
    command: pnpmBin,
    name: "Architecture"
  },
  {
    args: ["--filter", "@queue/web", "test", "--", "brand-ui", "discovery-ui", "roulette-ui"],
    command: pnpmBin,
    name: "Focused Phase 7 source/UI tests"
  },
  {
    args: ["--filter", "@queue/web", "exec", "playwright", "test", "tests/phase-7-visual.spec.ts"],
    command: pnpmBin,
    name: "Phase 7 visual browser evidence"
  },
  {
    args: ["--filter", "@queue/web", "test", "--", "roulette-ui"],
    command: pnpmBin,
    name: "Phase 6 preservation - roulette-ui"
  }
];

const commandResults = commands.map(runCommand);
const failedCommands = commandResults.filter((result) => result.status !== 0);
const result =
  failedCommands.length > 0
    ? "FAILED"
    : missingExternalEvidence.length > 0
      ? "BLOCKED - missing external evidence"
      : "PASSED";

writeEvidence({ commandResults, result });

console.log("");
console.log(`[phase:7:gate] Result: ${result}`);
console.log("[phase:7:gate] Command status:");
for (const commandResult of commandResults) {
  console.log(
    `[phase:7:gate] - ${commandResult.name}: ${
      commandResult.status === 0 ? "passed" : `failed (${commandResult.status})`
    }`
  );
}

if (missingExternalEvidence.length > 0) {
  console.log("");
  console.log("[phase:7:gate] Missing external evidence:");
  for (const name of missingExternalEvidence) {
    console.log(`[phase:7:gate] - ${name}`);
  }
}

console.log("");
console.log(`[phase:7:gate] Evidence summary: ${evidencePath}`);
console.log(`[phase:7:gate] Browser screenshots: ${screenshotDir}`);

if (failedCommands.length > 0 || missingExternalEvidence.length > 0) {
  process.exitCode = 1;
}

function runCommand(commandConfig) {
  console.log("");
  console.log(`[phase:7:gate] ${commandConfig.name}`);
  const commandLine = [commandConfig.command, ...commandConfig.args].join(" ");
  console.log(`$ ${commandLine}`);

  const startedAt = Date.now();
  const commandResult = spawnSync(commandLine, {
    cwd: workspaceRoot,
    env: process.env,
    shell: true,
    stdio: "inherit"
  });
  const durationMs = Date.now() - startedAt;
  const status = commandResult.status ?? 1;

  console.log(
    `[phase:7:gate] ${commandConfig.name}: ${status === 0 ? "passed" : "failed"} (${durationMs}ms)`
  );

  return {
    command: commandLine,
    durationMs,
    name: commandConfig.name,
    status
  };
}

function writeEvidence({ commandResults, result }) {
  const generated = new Date().toISOString();
  const commandTable = [
    "| Command | Status | Duration |",
    "| --- | --- | --- |",
    ...commandResults.map(
      (entry) =>
        `| ${entry.name} | ${entry.status === 0 ? "passed" : `failed (${entry.status})`} | ${entry.durationMs}ms |`
    )
  ].join("\n");

  const markdown = [
    "---",
    "phase: 07",
    "artifact: visual-evidence",
    `generated: ${generated}`,
    `result: ${result}`,
    "---",
    "",
    "# Phase 7 Visual Evidence",
    "",
    "This file is generated by `pnpm phase:7:gate`. It records command status, screenshot locations and named fixture blockers without writing secret values.",
    "",
    "## Scope",
    "",
    "- Public landing, compact public auth and pairing routes.",
    "- Authenticated shell, Home, Biblioteca, Descobrir, Roleta, Desafios, Hall, Dupla and Perfil.",
    "- Axe, reduced motion, screenshot, no horizontal overflow, no overlap and touch target checks.",
    "- SAFE-04/SAFE-05 preservation through architecture and secret scan commands.",
    "",
    "## Command Status",
    "",
    commandTable,
    "",
    "## Browser Screenshots",
    "",
    `- Directory: \`${screenshotDir}\``,
    "",
    "## Missing External Evidence",
    "",
    listOrNone(missingExternalEvidence),
    "",
    `## Result: ${result}`,
    ""
  ].join("\n");

  mkdirSync(dirname(evidencePath), { recursive: true });
  writeFileSync(evidencePath, markdown, "utf8");
}

function missingVars(names) {
  return names.filter((name) => !process.env[name]);
}

function listOrNone(items) {
  return items.length > 0 ? items.map((name) => `- ${name}`).join("\n") : "None.";
}

function loadEnvLocal() {
  const envPath = resolve(workspaceRoot, ".env.local");

  if (!existsSync(envPath)) {
    return;
  }

  const content = readFileSync(envPath, "utf8");

  for (const line of content.split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);

    if (!match) {
      continue;
    }

    const [, name, rawValue] = match;

    if (!name || process.env[name]) {
      continue;
    }

    process.env[name] = unquote(rawValue?.trim() ?? "");
  }
}

function unquote(value) {
  if (
    (value.startsWith("\"") && value.endsWith("\"")) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }

  return value;
}
